### ISSUE TITLE
直下掘りの回避ができて、WEで直下掘りを量産することができる

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/ChuoCity#69]
### 不具合の説明

https://gyazo.com/d2f36eb912b029468bed82109a115790
画像のように二つ並んで掘っていくとy50以下は掘れないが、エラー文が出ないまま掘れてしまう。

y50のブロックと地上のブロックで直下彫りで開けた穴は、`//copy`で量産できてしまう。

### 再現手順

1. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`//copy`」を実行する
2. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`//paste`」を実行する
3.量産可能

### スクリーンショット

https://gyazo.com/d2f36eb912b029468bed82109a115790

**Comment by book000** [comment]
本機能は中央市限定であり、ChuoCityプラグインの機能ですので移動しました。

---

そもそもこの機能は「悪気なく（または悪いことと知らず）、直下掘りを行うプレイヤーの対策」機能という認識です。

## 横2ブロックを交互に破壊することで直下掘りをすることについて

こちらは「既知の**仕様**」です。
地下に部屋を作りたいなどのプレイヤーがいるため、あえて回避手段を設けています。
この回避を行ってもY50以下については（WEを使わなければ）破壊できなくなっています。

## WEでの直下掘りについて（複製を含む）

こちらも把握はしています。
解決しない理由として、以下ふたつが挙げられます:

### 技術的な問題によるもの

FastAsyncWorldEditとの連携において、別の問題が発生しうるので対策を講じていません。

### 常識的・倫理的な考え方によるもの

この機能はルールを把握していないプレイヤーが悪気なく直下掘りをするなどして（なんでそんなことをわざわざするのか理解できませんが）、結果として処罰されたり軽度な前科として運営側の記録に残されてしまうことを防ぐための機能です。
もっとも、中央市のルールとして `Y67以下での「直下掘り」を禁止` していますし、これを回避するプレイヤーは処罰対象になります。([参考: 中央市ルール](https://wiki.jaoafa.com/中央市#ルール))

根本的に、わざわざWEを使って直下掘りをしたり、掘ったものを複製するプレイヤーは確実に悪意があります。
地下に部屋を作りたいなどクリエイティブサーバとして奨励されるべき行動を目的としていない、システム（プラグイン）の制限をわざわざ回避しようとするのは建築したいとかそういう問題ではなく、ただただ運営への妨害行為です。
今回これを対策したところでまた別の回避策が使われるでしょうし、いたちごっこにしかなりません。jao Minecraft Serverは「悪意のあるプレイヤーのいたちごっこをするためにあるサーバ」ではないので、必要以上の制限を設ける必要は無いと思っています。

以上、本問題への対応不要としてクローズします。
